/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ni_modinst_rf
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_NI_MODINST_RF_API_H
#define INCLUDED_NI_MODINST_RF_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ni_modinst_rf_EXPORTS
#define NI_MODINST_RF_API __GR_ATTR_EXPORT
#else
#define NI_MODINST_RF_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_NI_MODINST_RF_API_H */
