/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ni_rfsa_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1c622b84078e290d59d01f4f1c793695)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ni_modinst_rf/ni_rfsa_source.h>
// pydoc.h is automatically generated in the build directory
#include <ni_rfsa_source_pydoc.h>

void bind_ni_rfsa_source(py::module& m)
{

    using ni_rfsa_source    = gr::ni_modinst_rf::ni_rfsa_source;


    py::class_<ni_rfsa_source, gr::block, gr::basic_block,
        std::shared_ptr<ni_rfsa_source>>(m, "ni_rfsa_source", D(ni_rfsa_source))

        .def(py::init(&ni_rfsa_source::make),
           py::arg("resourceName"),
           D(ni_rfsa_source,make)
        )
        



        ;




}








